### ISSUE TITLE
CHECK_EQUAL and std::nullopt

### ISSUE THREAD

**Issue by kkayal** [drleq/CppUnitTestFramework#12]
I have used CHECK_EQUAL to verify a std::optional variable is std::nullopt and get the following compiler error:

```
CppUnitTestFramework.hpp:439:63: error: no matching function for
      call to 'ToString'
            auto msg = "[" + Ext::ToString(left) + "] == [" + Ext::ToString(right) + "]";
```

I had a look to the 'ToString' function and have seen that none of the constexpression checks catch a std::nullopt, so the function ends up with the last else block, which assumes std::to_string(value) can be used. This is where the compiler throws the above error.

I don't have have a good solution to this problem and therefore cannot offer a pull request. For now, I was able to mitigate it by inserting the following code before the last else:

```
            } else if constexpr (std::is_literal_type<T>::value) {
                // std::nullopt
                return "literal_type";
```

Hope this helps and someone can improve it.

**Comment by drleq** [comment]
Hi kkayal,

Thanks for taking the time to provide feedback!

In general, this situation can be handled by adding your own custom overloads for `CppUnitTestFramework::Ext::ToString()`.  These overloads can be templated to match against STL types such as `std::optional<>` and `std::nullopt`.

To keep the header as focused as possible I made a conscious decision to only include the simplest overloads for the default `ToString()`.  At the time this did not include `std::optional<>` or `std::nullopt`.  However, I've also encountered a few situations where I needed to use it (such as in [JsonCpp|https://github.com/drleq/CppJson/blob/master/Tests/ToString.h]) so I'd be happy to include this by default.

**Comment by drleq** [comment]
I've merged an update to [CppUnitTestFramework.hpp|https://github.com/drleq/CppUnitTestFramework/blob/master/CppUnitTestFramework.hpp] to include `std::optional<>` and `std::nullopt` support by default.  This will conflict with custom overloads that others have written for themselves, but this should be easy to resolve.
