### ISSUE TITLE
How to get this working with my Visual Studio Code after installing Extension?

### ISSUE THREAD

**Issue by rishitborad** [drleq/CppUnitTestFramework#14]
Hello,

Thanks for sharing this. Can you please share detailed steps on how to get this framework working with my Visual Studio Code workspace? I have extension installed. Should I copy this repo to my workspace? My test.cpp has trouble finding .hpp file. Also some more information on Configuration properties or example usage would really help. Apologise for inconvenience. I am new with Visual Studio Code. 

Thanks in advance.
Regards,
Rishit

**Comment by rfitzu** [comment]
Hi @rishitborad, 

      I am also a user Visual Studio Code user. Did you ever find an answer to your question above? I am in the same boat.

**Comment by drleq** [comment]
Closing this issue as off topic / won't address.  There are multiple ways of building a C++ project in VSCode (CMake, MSBuild etc) and this isn't the forum for covering them.
