### ISSUE TITLE
Different CppUnit macros

### ISSUE THREAD

**Issue by forrma** [drleq/CppUnitTestFramework#22]
I would like to create a Visual Studio 2022 project for existing UnitTests implemented for the CppUnit test framework. The tests should be visualized in the test explorer. The tests are additionally built in the Linux build environment.

In Visual Studio the plugin 'Test Adapter for CppUnitTestFramework' is installed. However, the plugin requires that the tests are implemented as follows:

#include "CppUnitTest.h"

using namespace Microsoft::VisualStudio::CppUnitTestFramework;

namespace UnitTest3
{
    TEST_CLASS(UnitTest3)
    {
    public:
        
        TEST_METHOD(TestMethod1)
        {
        }
    };
}

But my existing CppUnit tests have the following structure:

class TestCases : public CppUnit::TestFixture
{
    CPPUNIT_TEST_SUITE(TestCases);
    CPPUNIT_TEST(TestMethod1);
    CPPUNIT_TEST(TestMethod2);
    CPPUNIT_TEST_SUITE_END();
};

Do I need to implement my own C++ macros that convert the format to the appropriate format for Visual Studio and gcc? Or is there already something existing?

**Comment by drleq** [comment]
While this project shares a similar name with Microsofts own [CppUnitTestFramework](https://docs.microsoft.com/en-us/visualstudio/test/microsoft-visualstudio-testtools-cppunittestframework-api-reference?view=vs-2022) API they are completely unrelated.  I recommend reading their documentation or, if required, contacting them for support.
